[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 13

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Return"
mods = "Option|Shift"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
