theme = "solarized-dark"
[icons]
name = "awesome"
[icons.overrides]
music = ""

#[[block]]
#block = "music"
#player = "spotify"
#max_width = 36
#buttons = ["play", "next"]

[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid} {signal_strength} {speed_down;K*B}"
hide_inactive = true
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
format_mem = "{mem_avail;G}({mem_avail_percents:1})"
format_swap = "{swap_used;G}({swap_used_percents:1})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
info = 15
warning = 50
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "load"
format = "{1m} {5m}"
interval = 3

[[block]]
block = "temperature"
interval = 10
format = "{min} {max} {average}"

[[block]]
block = "time"
format = "%a %d/%m %T"
timezone = "Europe/Berlin"
interval = 60

[[block]]
block = "sound"
step_width = 3
on_click = "pavucontrol"

[[block]]
block = "custom"
command = "/home/sebas/bin/xkb-layout-icon.sh"
interval = 1
on_click = "xkb-switch -n"

[[block]]
block = "pacman"
interval = 3600

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
