theme = "solarized-dark"
[icons]
name = "awesome"
[icons.overrides]
music = ""

#[[block]]
#block = "music"
#player = "spotify"
#max_width = 36
#buttons = ["play", "next"]

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = false
speed_up = false
graph_up = false
speed_down = true
graph_down = false
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
format_mem = "{MAg}GB({MApi}%)"
format_swap = "{SUg}GB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
info = 15
warning = 50
interval = 1
frequency = true

[[block]]
block = "load"
format = "{1m} {5m} {15m}"
interval = 3

[[block]]
block = "temperature"
interval = 10
format = "{min}째 {max}째 {average}째"

[[block]]
block = "weather"
format = "{weather} {temp}째 {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "2f85ace6a523d52aecb1d86a9f9b2b0e", city_id = "2938913", units = "metric" }

[[block]]
block = "time"
format = "%a %d/%m %T"
timezone = "Europe/Berlin"
interval = 60

[[block]]
block = "sound"
step_width = 3
on_click = "pavucontrol"

[[block]]
block = "custom"
command = "/home/sebas/bin/xkb-layout-icon.sh"
interval = 1
on_click = "xkb-switch -n"

[[block]]
block = "pacman"
interval = 3600

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
