[user]
name = "Sebastian Stammler"
email = "seb@oplabs.co"

[aliases]
# general aliases
l = ["log", "--no-pager"]
c = ["commit"]
e = ["edit"]
sq = ["squash"]
bc = ["bookmark", "create"]

# git-like aliases
pt = ["git", "push", "--tracked"]
p- = ["git", "push", "--allow-new", "-r", "@-"]
pb = ["git", "push", "--allow-new", "-r", "trunk()..@-"]
f = ["git", "fetch"]
rbt = ["rebase", "-s", "roots(trunk()..@)", "-d", "trunk()", "--skip-emptied"]
sync = ["util", "exec", "--", "sh", "-c", """
jj f
jj rbt
""", ""]

[revset-aliases]
"immutable_heads()" = "present(trunk()) | (tags() ~ (tags(dev) | tags(synctest) | tags(cdfpl))) | untracked_remote_bookmarks()"

[ui]
diff-formatter = "ksdiff"
merge-editor = "ksdiff"

[merge-tools.ksdiff]
diff-invocation-mode = "file-by-file"
diff-args = ["--partial-changeset", "$left", "$right"]
merge-args = ["--merge", "--output", "$output", "--base", "$base", "$left", "$right"]
