[user]
name = "Sebastian Stammler"
email = "seb@oplabs.co"

[remotes.origin]
auto-track-bookmarks = "seb/*"
[remotes.upstream]
auto-track-bookmarks = "(main|master|develop)"
[templates]
git_push_bookmark = '"seb/push-" ++ change_id.short()'


[aliases]
# general aliases
l = ["log", "--no-pager"]
c = ["commit"]
e = ["edit"]
sq = ["squash"]
bc = ["bookmark", "create", "-r", "@-"]
nt = ["new", "trunk()"]

# git-like aliases
pt = ["git", "push", "--tracked"]
p- = ["git", "push", "-r", "@-"]
pc- = ["git", "push", "-c", "@-"]
pb = ["git", "push", "-r", "trunk()..@-"]
f = ["git", "fetch"]
rbt = ["rebase", "-s", "roots(trunk()..@)", "-d", "trunk()", "--skip-emptied"]
sync = ["util", "exec", "--", "sh", "-c", """
jj f
jj rbt
""", ""]

[revset-aliases]
"immutable_heads()" = "present(trunk()) | (tags() ~ (tags(dev) | tags(synctest) | tags(cdfpl)))" # | untracked_remote_bookmarks()"

[ui]
# diff-formatter = "ksdiff"
merge-editor = "ksdiff"

[merge-tools.ksdiff]
diff-invocation-mode = "file-by-file"
diff-args = ["--partial-changeset", "$left", "$right"]
merge-args = ["--merge", "--output", "$output", "--base", "$base", "$left", "$right"]
