icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[icons]
icons = "awesome6"
[icons.overrides]
music = ""

[[block]]
block = "music"
player = "spotify"
format = " $icon {$combo.str(max_w:36) $play $next |}"
#max_width = 36
#buttons = ["play", "next"]

[[block]]
block = "net"
device = "wlp2s0"
format = " $icon $ssid $signal_strength $speed_down.eng(prefix:K)"
#hide_inactive = true
#interval = 5

[[block]]
block = "disk_space"

[[block]]
block = "memory"
#format_mem = "{mem_avail;G}({mem_avail_percents:1})"
#format_swap = "{swap_used;G}({swap_used_percents:1})"
format = " $icon $mem_avail.eng(w:3,u:B,p:M) "
format_alt = " $icon_swap $swap_used.eng(w:3,u:B,p:M) "
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization $frequency{ $boost|} "

[[block]]
block = "load"
format = " $icon $1m.eng(w:4) $5m.eng(w:4) "
interval = 3

[[block]]
block = "temperature"
interval = 5
format = " $icon $min/$max/$average "

#[[block]]
#block = "weather"
#format = "{temp} {wind_kmh}km/h {direction}"
#service = { name = "openweathermap", api_key = "2f85ace6a523d52aecb1d86a9f9b2b0e", city_id = "2938913", units = "metric" }
#autolocate = false

[[block]]
block = "time"
#format = "%a %d/%m %T"
interval = 5

[[block]]
block = "sound"
step_width = 3

#[[block]]
#block = "custom"
#command = "/home/sebas/bin/xkb-layout-icon.sh"
#interval = 1
#on_click = "xkb-switch -n"

[[block]]
block = "pacman"
interval = 1200

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
format = " $icon $percentage $time $power "
